{% set version = "0.1.0" %}

package:
  name: pubgeo-tools
  version: {{ version }}

source:
  git_rev: 7980377ff68dc3f7a922a07a517cab2494aa6331
  git_url: https://github.com/msmolens/pubgeo.git
  patches:
    - fix-error-reading-tiff-input.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - cmake
    - ninja
    - libgdal
    - libpdal
  run:
    - libgdal
    - libpdal

about:
  home: http://www.jhuapl.edu/pubgeo.html
  license: MIT
  summary: Geospatial tools for 3D registration and scene classification
