package:
  name: flann
  version: 1.9.1

source:
  fn: 1.9.1.zip
  url: https://github.com/mariusmuja/flann/archive/1.9.1.zip
  sha256: 45420be368a76d1ea1d4337e8bd9b031d75a1abc01a1120a7ab9ea72a922e45f

requirements:
  build:
  run:

about:
  home: http://www.cs.ubc.ca/research/flann/
  license: BSD
  license_file: COPYING
  summary: 'Library for performing fast approximate nearest neighbor searches in high dimensional spaces.'

