package:
   name: pcl
   version: 1.8.1

source:
   url: https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.1.zip
   sha256: 5738bd0da05f32ef3f7500feffec8d8821b5eb327d70d5a0b28a7eaef69d46f9
   patches:

requirements:
   build:
      - vtk 
      - xorg-libsm
      - xorg-libx11
   run:

about:
   home: http://www.pointclouds.org
   license: BSD
   license_file: LICENSE.txt
   summary: 'A standalone, large scale, open project for 2D/3D image and point cloud processing.'
